Repository IATI/IATI-Datastore, pull requests merged in 2018-04, with the labels that each got.

#307 Update base URLs for the Registry
  iati_datastore/iatilib/crawler.py
Labels: bug, complete

#296 Merge master into live
  README.md
  datastore.wsgi
  iati_datastore/iatilib/crawler.py
  iati_datastore/setup.py
  requirements.txt
  requirements_dev.txt
Labels: enhancement

#304 Coverage should only include iati_datastore
  .coveragerc
Labels: waiting for dev datastore
